routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\KegiatanController;
use App\Http\Controllers\PeminjamController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PenjagaController;
use App\Http\Controllers\TimController;

// use App\Http\Controllers\KegiatanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::group(['middleware' => 'auth'], function () {
    Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);

    //TIM
    Route::resource('tim', TimController::class);

    //PENJAGA
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/penjaga/data', [App\Http\Controllers\PenjagaController::class, 'data'])->name('data');
    Route::resource('penjaga', PenjagaController::class);

    // KEGIATAN
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    // PEMINJAM
    Route::get('/peminjam', [App\Http\Controllers\PeminjamController::class, 'index'])->name('peminjam');
    Route::get('/peminjam/create', [PeminjamController::class, 'create'])->name('peminjam_tambah');
    Route::get('/peminjam/edit/{id_peminjam}', [PeminjamController::class, 'edit'])->name('peminjam_edit');

    Route::post('/peminjam/store', [PeminjamController::class, 'store'])->name('peminjam_store');
    Route::put('/peminjam/update/{id_peminjam}', [App\Http\Controllers\PeminjamController::class, 'update'])->name('peminjam_update');
    Route::get('/peminjam/destroy/{id_peminjam}', [App\Http\Controllers\PeminjamController::class, 'destroy'])->name('peminjam_delete');

    //gedung
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/gedung', [App\Http\Controllers\GedungController::class, 'index'])->name('gedung');
    Route::get('/gedung/tambah', [App\Http\Controllers\GedungController::class, 'tambah'])->name('gedung_tambah');
    Route::get('/gedung/edit/{id_gedung}', [App\Http\Controllers\GedungController::class, 'edit'])->name('gedung_edit');
    // Operation
    Route::post('/gedung/store', [App\Http\Controllers\GedungController::class, 'store'])->name('gedung_store');
    Route::put('/gedung/update/{id_gedung}', [App\Http\Controllers\GedungController::class, 'update'])->name('gedung_update');
    Route::get('/gedung/hapus/{id_gedung}', [App\Http\Controllers\GedungController::class, 'delete'])->name('gedung_delete');

    // kebersihan
    Route::get('/anggota_kebersihan', [App\Http\Controllers\AnggotaKebersihanController::class, 'index'])->name('anggota_kebersihan');
    Route::get('/anggota_kebersihan/create', [App\Http\Controllers\AnggotaKebersihanController::class, 'create'])->name('anggota_kebersihan_create');
    Route::get('/anggota_kebersihan/edit/{id}', [App\Http\Controllers\AnggotaKebersihanController::class, 'edit'])->name('anggota_kebersihan_edit');
    // Operation
    Route::post('/anggota_kebersihan/store', [App\Http\Controllers\AnggotaKebersihanController::class, 'store'])->name('anggota_kebersihan_store');
    Route::put('/anggota_kebersihan/update/{id}', [App\Http\Controllers\AnggotaKebersihanController::class, 'update'])->name('anggota_kebersihan_update');
    Route::get('/anggota_kebersihan/destroy/{id}', [App\Http\Controllers\AnggotaKebersihanController::class, 'destroy'])->name('anggota_kebersihan_delete');


    //rekap
    Route::get('/rekap', 'App\Http\Controllers\RekapController@index')->name('rekap');
    Route::get('/rekap/tambah', 'App\Http\Controllers\RekapController@create')->name('tambah');
    Route::get('/rekap/edit/{id_rekap}', 'App\Http\Controllers\RekapController@edit')->name('edit');
    Route::put('/rekap/update/{id_rekap}', 'App\Http\Controllers\RekapController@update')->name('update');
    Route::get('/rekap/delete/{id_rekap}', 'App\Http\Controllers\RekapController@destroy')->name('delete');
    Route::post('/rekap', 'App\Http\Controllers\RekapController@store')->name('rekap');

    // KEGIATAN
    // Route::get('/kegiatan', [App\Http\Controllers\KegiatanController::class, 'index'])->name('kegiatan');
    Route::get('/kegiatan', [App\Http\Controllers\KegiatanController::class, 'index'])->name('kegiatan');
    Route::get('/kegiatan/tambah', [App\Http\Controllers\KegiatanController::class, 'tambah'])->name('kegiatan_tambah');
    Route::get('/kegiatan/edit/{id_kegiatan}', [App\Http\Controllers\KegiatanController::class, 'edit'])->name('kegiatan_edit');
    // Operation
    Route::post('/kegiatan/store', [App\Http\Controllers\KegiatanController::class, 'store'])->name('kegiatan_store');
    Route::put('/kegiatan/update/{id_kegiatan}', [App\Http\Controllers\KegiatanController::class, 'update'])->name('kegiatan_update');
    Route::get('/kegiatan/hapus/{id_kegiatan}', [App\Http\Controllers\KegiatanController::class, 'delete'])->name('kegiatan_delete');
});

app/Models/Tim.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tim extends Model
{
    use HasFactory;

    protected $table = "tim_kebersihan";

    protected $fillable = ["nama_tim"];
}

app/Http/Controllers/TimController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tim;
use App\Models\Gedung;
use Illuminate\Http\Request;

class TimController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $datas = tim::orderBy('nama_tim', "ASC")->get();
        $headerdata = Gedung::orderBy('kapasitas', "DESC")->get();
        return view('tim.index',compact('datas'))->with('headerdata', $headerdata);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $headerdata = Gedung::orderBy('kapasitas', "DESC")->get();
        return view("tim.create")->with('headerdata', $headerdata);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama_tim' => 'required',
        ]);

        Tim::create($request->all());

        return redirect()->route('tim.index')->with('success', 'Tim created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Tim  $tim
     * @return \Illuminate\Http\Response
     */
    public function show(Tim $tim)
    {
       //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Tim  $tim
     * @return \Illuminate\Http\Response
     */
    public function edit(Tim $tim)
    {
        $headerdata = Gedung::orderBy('kapasitas', "DESC")->get();
        return view('tim.edit', compact('tim'))->with('headerdata', $headerdata);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Tim  $tim
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tim $tim)
    {
        $request->validate([
            'nama_tim' => 'required',
        ]);

        $tim->update($request->all());
        return redirect()->route('tim.index')->with('success', 'Tim has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Tim  $tim
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tim $tim)
    {
        $delete = $tim->delete();
        return redirect()->route('tim.index')->with('success','Tim ha been deleted successfully');
    }
}

resources/views/tim/create.blade.php
@extends('layouts.app')

@section('content')
    @include('layouts.headers.cards')
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="xyz align-items-center">
                            <div class="col-12">
                                <h3 class="mb-0">Form Tambah Tim</h3>
                            </div>
                            <p>
                            <form method="POST" action="{{ route('tim.store') }}">
                                @csrf
                                <div class="row">
                                    <div class="col-12">
                                        <div class="form-group">
                                            <input type="text" class="form-control" name="nama_tim" placeholder="Nama Tim">
                                            @if ($errors->has('nama_tim'))
                                                <div class="text-danger">
                                                    {{ $errors->first('nama_Tim') }}
                                                </div>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <button type="submit" class="btn btn-success">Tambahkan</button>
                                    </div>
                                </div>
                            </form>
                            <div class="card-footer py-4">
                                <nav class="d-flex justify-content-end" aria-label="...">

                                </nav>
                            </div>
                        </div>
                    </div>
                </div>

                @include('layouts.footers.auth')
            </div>
        </div>
    </div>
@endsection


@push('js')
    <script src="{{ asset('argon') }}/vendor/chart.js/dist/Chart.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/chart.js/dist/Chart.extension.js"></script>
    <script src="{{ asset('argon') }}/vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
@endpush

resources/views/tim/edit.blade.php
@extends('layouts.app')

@section('content')
    @include('layouts.headers.cards')
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="xyz align-items-center">
                            <div class="col-12">
                                <h3 class="mb-0">Form Edit Tim</h3>
                            </div>
                            <p>
                            <form method="POST" action="{{ route('tim.update', $tim->id) }}">
                                @csrf
                                @method('PUT')
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <input type="text" class="form-control" name="nama_tim"
                                                placeholder="Nama Tim" value="{{ $tim->nama_tim }}">
                                            @if ($errors->has('nama_tim'))
                                                <div class="text-danger">
                                                    {{ $errors->first('nama_tim') }}
                                                </div>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <button type="submit" class="btn btn-success">Simpan</button>
                                    </div>
                                </div>
                            </form>
                            <div class="card-footer py-4">
                                <nav class="d-flex justify-content-end" aria-label="...">

                                </nav>
                            </div>
                        </div>
                    </div>
                </div>

                @include('layouts.footers.auth')
            </div>
        </div>
    </div>
@endsection


@push('js')
    <script src="{{ asset('argon') }}/vendor/chart.js/dist/Chart.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/chart.js/dist/Chart.extension.js"></script>
    <script src="{{ asset('argon') }}/vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
@endpush

resources/views/tim/index.blade.php
@extends('layouts.app')

@section('content')
    @include('layouts.headers.cards')

    {{-- <style type="text/css">
		.pagination li{
			float: left;
			list-style-type: none;
			margin:5px;
		}
	</style> --}}

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">Tim</h3>
                                @if ($message = Session::get('success'))
                                    <div class="alert alert-success">
                                        <p>{{ $message }}</p>
                                    </div>
                                @endif
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('tim.create') }}" class="btn btn-sm btn-primary">Tambah Tim</a>
                            </div>
                            <br>
                            <br>
                            @if (count($datas) > 0)
                                <div class="table-responsive">
                                    <table class="table table-condensed table-bordered table-hover table-flush">
                                        <thead class="thead-light">
                                            <tr>
                                                <th class="text-center">No</th>
                                                <th class="text-center">Nama Tim</th>
                                                <th class="text-center">Opsi</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($datas as $data)
                                                <tr>
                                                    <td class="text-center">{{ $loop->iteration }}</td>
                                                    <td class="text-center">{{ $data->nama_tim }}</td>
                                                    <td class="text-center">
                                                        <a type="button" href="{{ route('tim.edit', $data->id) }}" class="btn btn-success btn-sm"><i class="fa fa-edit"></i></a>
                                                        <form class="d-inline" method="POST" action="{{ route('tim.destroy', $data->id) }}">
                                                            @csrf
                                                            @method('DELETE')
                                                            <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></button>
                                                        </form>
                                                    </td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                    <br />
                                </div>
                            @else
                                <br>
                                <div class="col-12 text-center">
                                    <span class="badge badge-warning">Belum ada data</span>
                                </div>
                            @endif
                            <div class="card-footer py-4">
                                <nav class="d-flex justify-content-end" aria-label="...">

                                </nav>
                            </div>
                        </div>
                    </div>
                </div>

                @include('layouts.footers.auth')
            </div>
        @endsection

        @push('js')
            <script src="{{ asset('argon') }}/vendor/chart.js/dist/Chart.min.js"></script>
            <script src="{{ asset('argon') }}/vendor/chart.js/dist/Chart.extension.js"></script>
            <script src="{{ asset('argon') }}/vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
        @endpush